### ISSUE TITLE
I want to make the UI look better using CSS and graphic designs 

### ISSUE THREAD

**Issue by Munya-Marinda** [HopeInTech/Tic-Tac-Toe-#1]
I attached an example of a design that I would create.

![portrait-screenshots-5](https://github.com/HopeInTech/Tic-Tac-Toe-/assets/84540577/c194243e-6aa8-4986-a2d2-34fd7597f0ca)

**Comment by HopeInTech** [comment]
Alright, go ahead and let me see!, 🙂
